import './layout/container'
import './loader/loader'
import './menu/menu'
import './sections/brands/brands'
import './sections/features/feature'
import './sections/footer/footer'
import './sections/hero/hero'
import './sections/pricing/pricing'
